scrolling:
    history: 16384

font:
    normal:
        family: "MesloLGS NF"
        style: Regular

    bold:
        family: "MesloLGS NF"
        style: Bold

    italic:
        family: "MesloLGS NF"
        style: Italic
        
    bold_italic:
        family: "MesloLGS NF"
        style: Bold Italic

    size: 10

colors:
    primary:
        # background: '0x2c2c2c'
        background: '0x111111'
        foreground: '0xd6d6d6'

        dim_foreground:    '0xdbdbdb'
        bright_foreground: '0xd9d9d9'
        dim_background:    '0x202020'
        bright_background: '0x3a3a3a'

    cursor:
        text:   '0x2c2c2c'
        cursor: '0xd9d9d9'

    normal:
        black:   '0x1c1c1c'
        red:     '0xbc5653'
        green:   '0x909d63'
        yellow:  '0xebc17a'
        # blue:    '0x7eaac7'
        blue:    '0x6070c7'
        magenta: '0xaa6292'
        cyan:    '0x86d3ce'
        white:   '0xcacaca'

    bright:
        black:   '0x636363'
        red:     '0xbc5653'
        green:   '0x909d63'
        yellow:  '0xebc17a'
        # blue:    '0x7eaac7'
        blue:    '0x6070c7'
        magenta: '0xaa6292'
        cyan:    '0x86d3ce'
        white:   '0xf7f7f7'

    dim:
        black:   '0x232323'
        red:     '0x74423f'
        green:   '0x5e6547'
        yellow:  '0x8b7653'
        blue:    '0x556b79'
        magenta: '0x6e4962'
        cyan:    '0x5c8482'
        white:   '0x828282'

background_opacity: 0.9

